feat: jotai setting 및 auth 관련 전역상태 관리
depromeet/amazing3-fe pull request #11
Opened 2023-12-01 13:16 UTC by Doeunnkimm

## 🤔 해결하려는 문제가 무엇인가요?
- [Jotai 설정 및 auth state 추가 및 사용 코드 작성](https://www.notion.so/depromeet/Jotai-auth-state-09378753501f47868e754e095af298b0)

## 🎉 어떻게 해결했나요?
- jotai 패키지 설치
- auth 관련 전역상태 관리
- custom hook 정의

아래 이미지는 (좀 대충이긴 하지만..) 사용 예시입니다 🙌
![image](https://github.com/depromeet/amazing3-fe/assets/112946860/237bde71-62ff-4fcd-99a7-457d7b4edd57)

### 📚 Attachment (Option)
로그인 시 받아지는 데이터 형태에 대해서는 어떻게 관리될지 정해지지 않은 것 같아서! 우선 관련되어 필요할 것 같은 상태들 넣어두었습니당
[상태 종류들은 인사이트 아웃 참고](https://github.com/depromeet/InsightOut-client/blob/main/src/features/auth/store/index.ts)했움다.. ⭐️ (민경님 절 너무 부담스러워하진 말아주세요,, ⎝⍥⎠ ,,

2023-12-03 16:06 UTC, deepbig reviewed
역시 도은 동생..!!!! 아주 훌륭해~!! 👍 💯  👍💯  👍 💯 👍 💯  

조금 더 의논해보고 화요일에 같이 merge 할까요~???

2023-12-04 01:35 UTC, Doeunnkimm commented on src/features/auth/hooks/useAuthStore.ts
네넹!!! 저는 관련된 건 같은 폴더에 놓으려는 습관이 있어서 이 부분에 대해서 화요일에 마저 이야기 해보면 좋을 거 같아요!!!

2023-12-05 14:48 UTC, hjy0951 approved these changes
PR을 볼 때마다 처음 보는 것들이 많아서 매번 많이 배워갑니다...🫡

2023-12-05 14:48 UTC, hjy0951 commented on src/features/auth/store/index.ts
> 하지만, jotai가 global이 아닌 local 단위에서 상태 관리가 가능하니 도은님 처럼 feature 하위에 위치 시키는 방식을 가이드하는 분들도 많이 있어서 고민이 되네요~!

이 말씀은 `useState` 대신 `jotai`를 `local state`를 관리하는데에도 사용되어서 그렇다는 말씀이신건가요?!

2023-12-06 07:53 UTC, deepbig requested changes
Best practice로 찾은 directory 구조와 atom 사용 방식에 따른 내용 공유드립니다. 

Best practice는 [카카오스타일 기술블로그](https://devblog.kakaostyle.com/ko/2022-01-13-2-jotai-recipe/)를 참고했습니다. 

Jotai는 atom의 모음
값은 `atoms` 디렉토리 (atoms는 연관성이 높은 것들을 한 파일로 묶고)
액션은 `actions` 디렉토리로 묶음 (액션은 보통 길이가 길기 때문에 액션 별로 파일을 만듦)
```
src
ㄴ features
	ㄴ auth
		ㄴ store
			ㄴ index.ts // 베럴 파일
			ㄴ atoms // value들의 모음
				ㄴindex.ts // feature에서 공통으로 사용되는 부분
				ㄴ user.ts // 연관성이 높은 것들의 모음 (있을 시)
			ㄴ actions // 동작의 모음
				ㄴ index.ts // feature에서 공통으로 사용되는 부분
				ㄴlogin.ts // action별 모음
```
store 내용
```
// src/features/auth/store/index.ts 
export * from './atoms';
export * from './actions';
```

store/atoms 내용
```
// src/features/auth/store/atoms/index.ts
import { atom } from 'jotai';

export * from './user';

export const submitting_atom = atom(false);
```

store/atoms/user.ts
```
export const user_email_atom = atom(''); 
export const user_name_atom = atom('');
export const user_password_atom = atom('');
```

store/actions 내용
```
// src/features/auth/store/actions/index.ts
export * from './login';
```

store/actions/login
```
import { atom } from 'jotai';
import {
  user_email_atom, 
  user_name_atom,
  ...
} from '../atoms';

export const loginAtom = atom(null, async (get, set) => { 
  const user_email = get(user_email_atom); 
  ...
});
```

위 처럼 진행한다고 했을 시에 현재 PR이 많이 수정돼야 할 것 같습니다. 혹시 힘드시면 도은님 시간 되실 때 게더에서 같이 페어코딩하시죠~~ (혼자가 편하시면 혼자하셔도 돼요!! 흑흑)

2023-12-06 07:53 UTC, deepbig commented on src/features/auth/types/store.ts
> +/**
AuthStateProps type 위 처럼 반영하면 해당 타입이 불필요할 것 같아요.

2023-12-06 07:53 UTC, deepbig commented on src/features/auth/store/index.ts
> +});
AuthStateProps type으로 묶지 말고 위의 best practice처럼 각각을 import하는 게 어떨까요?

2023-12-06 07:53 UTC, deepbig commented on src/features/auth/hooks/useAuthStore.ts
> +  const setIsRequesting = (value: AuthStateProps['isRequesting']) => setAuthStore({ isRequesting: value });
`useSetAtom`이 있는데 set 함수를 만들 필요가 있을까요~?

2023-12-06 14:06 UTC, merged