fix: icon.ico -> favicon.ico 변경
depromeet/amazing3-fe pull request #88
Opened 2024-01-02 15:54 UTC by minkyung00

## 🤔 해결하려는 문제가 무엇인가요?

- 구글 검색 시, favicon이 보이지 않는 이슈

## 🎉 어떻게 해결했나요?

| AS-IS | TO-BE |
|--------|--------|
| <img width="671" alt="스크린샷 2024-01-03 오전 12 43 28" src="https://github.com/depromeet/amazing3-fe/assets/80238096/18f1b794-8d36-4da7-9257-f6db286044d5"> | <img width="675" alt="스크린샷 2024-01-03 오전 12 43 20" src="https://github.com/depromeet/amazing3-fe/assets/80238096/9239ef5c-bc8d-4d5b-a61c-d68964f7a56d"> |
| favicon 32x32 | favicon 48x48 | 

- favicon.ico가 없는데 32x32로 잡혀있어서 `icon.ico` -> `favicon.ico`로 변경했습니다!

구글 가이드라인 보니까 48배수 사이즈여야한다고 해서 .. 킹리적 갓심으로 수정해봤습니다
<img width="300" alt="image" src="https://github.com/depromeet/amazing3-fe/assets/80238096/e9e79008-c76c-4bd2-bba4-87c1af5d858c">

<br />

그리고 next에서 favicon.ico의 사이즈를 any -> 실제 사이즈로 반영하도록 수정해서 any로 안뜨는게 맞는 것 같습니다~
- https://github.com/vercel/next.js/commit/de873d02b3b9bbe6852485358acefe7011359e17

### 📚 Attachment (Option)
- 이래도 적용 안되면 다시 롤백할게요 🗿

2024-01-02 16:09 UTC, hjy0951 approved these changes
워우 이걸 벌써....
고생하셨습니다!
기도해봅시다 🙏

2024-01-02 16:13 UTC, deepbig requested changes
반영 전 확인확인 필요~!

2024-01-02 16:13 UTC, deepbig commented on src/app/icon.ico
오이오이 누민경 센세 icon.ico는 삭제하면 안돼~ 다른 놈이여~

참고:[ favicon, icon, and apple-icon](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons) 
관련 PR: https://github.com/depromeet/amazing3-fe/pull/81

2024-01-02 16:13 UTC, deepbig commented on src/app/favicon.ico
이거 최신 main에 있어요~!!

2024-01-02 16:16 UTC, deepbig commented on src/app/favicon.ico
아하 수정으로 표기되어 있네영 굿굿굿굿

2024-01-03 03:39 UTC, minkyung00 commented on src/app/icon.ico
아 저는 favicon 대신에 icon을 쓰고 있는 줄 알았습니다~

지금 icon.ico는 어디서 사용되고 있는지 알 수 있을까요?! next문서만 봤을 때에는 세분화해서 사용하는 경우에 icon을 쓴다고해서요!

2024-01-03 04:44 UTC, deepbig commented on src/app/icon.ico
next 문서의 icon 항목에 외부 링크로 설명한 부분이 있습니다. (이거:
: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) 여기에서 대부분의 브라우저의 icon을 지원하기 위해 `favicon`과 별개로 `icon`을 등록하는데 일단 되는지 테스트 해보려고 svg가 아닌 ico 포멧으로 등록한 상태에요~!

현 main branch에 favicon.ico를 32x32로 설정한 이유는 위 문서에서 설명한 버그 (`chrome에서 favicon 32x32 사이즈 외 파일 적용 안되는 버그`)를 회피하기 위해 32x32로 적용한 것이기도 합니다~!

2024-01-03 05:02 UTC, deepbig commented on src/app/icon.ico
흠... 그럼 일단 민경님 하고 싶은대로 한 번 변경해볼까요?? 안되면 나중에 다시 추가하지 뭐~~

반영 ㄱㄱ~~~~~~~!

2024-01-03 05:03 UTC, deepbig approved these changes
머지 ㄱㄱ~~~~~~ 해봤는데 안되면 icon.ico를 svg 로 변경해서 다시 시도해보죠~!!

2024-01-03 06:49 UTC, minkyung00 commented on src/app/icon.ico
@deepbig

2024-01-06 04:19 UTC, deepbig commented
지금 구글 검색에서 favicon 출력되네요~! 이거 반영 안해도 될 듯합니다~~!

![image](https://github.com/depromeet/amazing3-fe/assets/34956359/70e4c1be-b06c-4faf-a56c-fc1d3103312f)

2024-01-07 04:55 UTC, minkyung00 commented
> @minkyung00 지금 구글 검색에서 favicon 출력되네요~! 이거 반영 안해도 될 듯합니다~~!
> 
> ![image](https://private-user-images.githubusercontent.com/34956359/294647665-70e4c1be-b06c-4faf-a56c-fc1d3103312f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDM2MDIsIm5iZiI6MTcwNDYwMzMwMiwicGF0aCI6Ii8zNDk1NjM1OS8yOTQ2NDc2NjUtNzBlNGMxYmUtYjA2Yy00ZmFmLWE1NmMtZmMxZDMxMDMzMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA0NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YmFlODYzYzgwNDU2YmQ2YzRkNjQwMTBlMzRlMjk1ZDAyYzM2ZDdmM2NhY2ZhNzE5YjE3YjAyMjM4NTZlODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eISRb9IUzLoaYSAW9l9v1kUaVJGtwaP9e2lewlIm89s)

@deepbig 오! 다행이네요! 바로 클로즈하겠습니다~

2024-01-07 04:55 UTC, closed without merging